=== babcca/XML/DU 1/nazev.dtd
<!-- Address specification -->
<!ELEMENT address (street, city, postal)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT postal (#PCDATA)>
<!-- Agend specification -->
<!ELEMENT agents (agent*)>
<!ELEMENT agent (name, email, password, identification, registration, address, settings)>
<!ELEMENT settings (printers?)>
<!ELEMENT printers (print+)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT identification (#PCDATA)>
<!ELEMENT registration (#PCDATA)>
<!ELEMENT print EMPTY>
<!ATTLIST agent id ID #REQUIRED>
<!ATTLIST print 
	name CDATA #REQUIRED
	offset_x CDATA #REQUIRED
	offset_y CDATA #REQUIRED
>
<!-- Client spefication -->
<!ELEMENT clients (client*)>
<!ELEMENT client (name, subject, address)>
<!ELEMENT subject (subject_id)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT subject_id (#PCDATA)>
<!ATTLIST client id ID #REQUIRED>
<!ATTLIST subject_id type (date|number) #REQUIRED>
<!ATTLIST subject 
	type (pravni|fyzicka) #REQUIRED 
	dph (true|false) #REQUIRED
>




<!ELEMENT database ANY>

=== babcca/XML/DU 1/nazev.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE database SYSTEM "./nazev.dtd">
<database>
	<!-- Seznam vsech pojistovacich agentu, vyuzivacich teto program -->	
	<agents>
		<agent id="a0">
			<name>Petr Babicka</name>
			<email>babcca@gmail.com</email>
			<password>asd8s890adas89s0asd890ada678</password>
			<identification>1231321331</identification>
			<registration>2143241241</registration>
			<address>
				<street>V hlusinach 12</street>
				<city>Svetla nad Sazavou</city>
				<postal>58291</postal>
			</address>
			<settings>
				<printers>
					<print name="hp2110" offset_x="5" offset_y="10" />
					<print name="ineo210" offset_x="0" offset_y="0" />
				</printers>
			</settings>
		</agent>
	</agents>
	<clients>
		<client id="c0">
			<name>Karel Omacka</name>
			<subject type="fyzicka" dph="false">
				<subject_id type="date">12.12.1989</subject_id>
			</subject>
			<address>
				<street>V hlusinach 12</street>
				<city>Svetla nad Sazavou</city>
				<postal>58291</postal>
			</address>
		</client>
	</clients>
		
		
		
		
		
</database>
